### ISSUE TITLE
Double location bug

### ISSUE THREAD

**Issue by Cryinghawke** [WulfMarius/Show-Map-Location#3]
![20180218043443_1](https://user-images.githubusercontent.com/34219174/36347675-e9feca48-1465-11e8-957f-85922c19db19.jpg)

took a picture of the bug

encountered double map location X while mapping out the Muskeg region. I have only just installed the "remove campfire" mod but I don't know if it is related.

1 location is static and the other follows me perfectly. I can't seem to replicate what caused this. The extra X persists over a complete shutdown of the game.

**Comment by Cryinghawke** [comment]
the extra X also persists after removing the dll file altogether.

**Comment by WulfMarius** [comment]
I couldn't replicate this by normal gameplay, but it seems that the location is not removed when the maps is being closed.  
There's some check in there that will only remove the marker if it is exactly at the expected coordinates and I guess that check failed for some reason.

All remaining markers will now be removed when loading the game or changing the region.  
So this might still happen but will eventually correct itself.

Fixed with version 1.0.4


Thanks for reporting this!
